wipe = true
no-tests = true
add-global-variants	= true
pkgname= "dbcontext"
output= "app/infrastructure/db/models"

[psql]
  dbname  = "TigerDb"
  host    = "localhost"
  port    = 5432
  user    = "admin"
  pass    = "admin"
  sslmode = "disable"
  blacklist = ["postgres"]